name: istanbul-real-estates
favicon: null
layout_spectrum: 0.66702772048302
typography_spectrum: 0.6754374499432743
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#dbd1c4'
    - '#234550'
    - '#a5998d'
    - '#68615a'
  brandStrength: 0.19177667167969048
  lightness: 0.8432930328417569
  saturation: 0.6117851135786623
  rhythmicContrast: 0.45645345002412796
purpose: []
